AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for HelloWorld

Parameters:
  WebhookUri:
    Type: String
    Description: The WebHook URI to post the event to

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  AlarmPostToWebHook:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 128
      Environment:
        Variables:
          WEBHOOK_URI: !Sub ${WebhookUri}
          
    Metadata:
      DockerTag: dotnetcore3.1-v1
      DockerContext: ./src/AlarmPostToWebHook
      Dockerfile: Dockerfile
      DockerBuildArgs:
        SAM_BUILD_MODE: run
